### ISSUE TITLE
Bug where whenever me or someone else gets to the second round randomly, we jsut cant interact with anything 

### ISSUE THREAD

**Issue by Demeanors** [j-trueman/MultiplayerClient#2]
i did this experiment with 2 people, one of my friends in a vc and a random and it happened to me twice with the friend in my voice chat, and when i randomly found a random, it happened twice to them in a row. hope to see this fixed, also i have no idea how to run that dedicated server at all, just a thing to add i tried following the instructions and it didnt quite work out, you gotta make a video tutorial or something

**Comment by MSLaFaver** [comment]
This should be fixed with 0.2.1! We'll work on better documentation before any official release.
